### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by lzghades** [emilianavt/OpenSeeFaceSample#1]
Hello, could you give the step, how to run this demo project?

**Comment by emilianavt** [comment]
Hi, you can run it by running the included Scene in the scenes folder. To run the face tracking, you will also have to run [OpenSeeFace](https://github.com/emilianavt/OpenSeeFace) separately. If you are on Windows, you can add an OpenSeeFaceLauncher component on the OpenSee object and enter the necessary paths corresponding to your OpenSeeFace folder (facetracker.exe and model folder).

**Comment by jayp84847** [comment]
Is there any way, to run openseeface face tracking module inside unity and can deploy some kind of faceAR .

**Comment by emilianavt** [comment]
If you are on Windows and have the binary build, you can launch it through the OpenSeeFaceLauncher component. I'm not sure what you mean by faceAR.

**Comment by jayp84847** [comment]
Like I want to ask can I make snapchat like filter with this in unity?

**Comment by emilianavt** [comment]
In theory it should be possible, but I have never looked into that.

**Comment by jayp84847** [comment]
Can you help me for that?

**Comment by emilianavt** [comment]
I have more than enough things to work on as is. 😅
