### ISSUE TITLE
 'OVRLipSync' does not contain a definition for 'ProcessFrameInterleaved'

### ISSUE THREAD

**Issue by RoseFireCreations** [emilianavt/OpenSeeFaceSample#2]
as the title say i recieve this error (in full) 
Assets\OpenSeeFaceSample-master\Assets\OpenSeeFace\OpenSeeVRMDriver.cs(1626,44): error CS0117: 'OVRLipSync' does not contain a definition for 'ProcessFrameInterleaved'
this happens after un-commenting the first three lines as directed to get the OVR lipsync to work with this.

**Comment by emilianavt** [comment]
Hi, please make sure you are using version 1.20.0 of OVRLipSync. New versions changed the API and I haven't updated it yet.

**Comment by RoseFireCreations** [comment]
ah that would be the issue. thanks for the info.
