### ISSUE TITLE
dont install into unity.

### ISSUE THREAD

**Issue by anakein** [emilianavt/OpenSeeFaceSample#7]
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/emilianavt/OpenSeeFaceSample.git]:
  [https://github.com/emilianavt/OpenSeeFaceSample.git] does not point to a valid package. No package manifest was found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by emilianavt** [comment]
It's not a package, it's a full project. You clone the repository and add it as a project in Unity Hub.

**Comment by anakein** [comment]
thanks.
